# Generated by Django 4.1 on 2022-08-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('a_name', models.TextField()),
                ('amount', models.IntegerField()),
                ('payment', models.BooleanField(default=False)),
                ('paid_to', models.CharField(max_length=100)),
            ],
        ),
    ]
